### PR TITLE
Transferring  codebase from notion to here

### PR DESCRIPTION
**Pull request by poppyseedDev**
#2 Fixing issue

### CODE REVIEW

**Comment by poppyseedDev** [comment]
Couldn't resolve issue with netlify maybe there are some config issues. Tried with vercel and it works instantly:
 https://subwork.vercel.app/

**Comment by yangwao** [comment]
> By default, VitePress stores its dev server cache in .vitepress/cache, and the production build output in .vitepress/dist. If using Git, you should add them to your .gitignore file. These locations can also be [configured](https://vitepress.dev/reference/site-config#outdir).

and please give us back `package.json` to `/docs`  🥹

**Comment by poppyseedDev** [comment]
moved package.json into docs

**Comment by poppyseedDev** [comment]
Why aren't the changes in the codebase visible?

**Comment by poppyseedDev** [comment]
Can somebody with write access merge this codebase?

**Comment by yangwao** [comment]
> Can somebody with write access merge this codebase?


https://github.com/kodadot/subwork/assets/5887929/51409b38-4497-4200-9976-7a8d02befb1d

**Comment by yangwao** [comment]
I would make it separate sections each page
- Who we are - identifying as crypto & AI hub in Slovenia
- Where we are - away from cities, at Julian Alps with best air in the class
- When you are open -> can be refurbished to we are open daily to membership who has keys, public hours for new comers are usually in afternoon on weekdays
- Contact section -> It's possible to add icons? 
- Amenities
- High-speed low-latency optic Internet with superior WiFi6 801.11ax coverage
- Over 30 plants over all space
- Collaboration areas 
- Standing desk
- Two meeting rooms with capacity 8 and 6 people
- Most of hot desks are equipped with 4k usb-c 32" monitors - plenty real estate for your productivity
- Podcasting equipment for your video episodes with high performance gaming microphones and studio lighting and 1080p cam
- Conference capacities -> Organizing bigger hackathon in Bled or team retreat for 80+ folks?
- Subwork desires -> I would remove
- Food & Drinks -> We have over 10 brands of speciality coffees, Club-Mate and lot of productivity drinks in stock
- Shower -> Are you feeling sporty and keeping your morning workout finish in SubWork? We've got shower in space. \
- Why we choose Bled section
- Sports section incoming
  - #21 
- I would delete archive

- I would put telegram to the navbar - https://t.me/+VoZsr7MEds84ZjQ0

**Pull request merged**
